const IDENTIFIER = '@auth/';

export const FETCH_AUTH_SUCCESS = `${IDENTIFIER}FETCH_SUCCESS`;
export const FETCH_AUTH_REQUEST = `${IDENTIFIER}FETCH_REQUEST`;
export const FETCH_AUTH_FAIL = `${IDENTIFIER}FETCH_FAIL`;